export default {
    storageKeyCategories: 'categories',
    storageKeyDarkmode: 'dark',
    storageKeyDefault: 'default',
    storageKeyNewTab: 'newtab',
    storageKeyShowRecent: 'showrecent',
    storageKeyFirstUse: 'firstuse',
    storageKeyFirstUseOptions: 'firstuseoptions',
    storageKeyTerms: 'terms',
    storageMaxTerms: 2000,
    storageKeyEditmode: 'editable',
    transportFileNameJson: 'searchy.json',
    transportFileNameStatic: 'searchy.js',
    initialDataFile: 'initial_data_deploy.json',
}
